name: dbabandits
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _tflow_select=2.3.0=mkl
  - abseil-cpp=20210324.2=h2531618_0
  - absl-py=2.1.0=py38h06a4308_0
  - aiohttp=3.9.5=py38h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - astor=0.8.1=py38h06a4308_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - astunparse=1.6.3=py_0
  - async-timeout=4.0.3=py38h06a4308_0
  - attrs=23.1.0=py38h06a4308_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - blas=1.0=mkl
  - blinker=1.6.2=py38h06a4308_0
  - bottleneck=1.3.7=py38ha9d4c09_0
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.8.30=hbcca054_0
  - cachetools=5.3.3=py38h06a4308_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cffi=1.15.1=py38h74dc2b5_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.7=py38h06a4308_0
  - cryptography=41.0.3=py38h130f0dd_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - executing=2.1.0=pyhd8ed1ab_0
  - flatbuffers=2.0.0=h2531618_0
  - frozenlist=1.4.0=py38h5eee18b_0
  - gast=0.4.0=pyhd3eb1b0_0
  - giflib=5.2.1=h5eee18b_3
  - google-auth=2.29.0=py38h06a4308_0
  - google-auth-oauthlib=0.4.1=py_2
  - google-pasta=0.2.0=pyhd3eb1b0_0
  - grpcio=1.42.0=py38hce63b2e_0
  - h5py=3.9.0=py38he06866b_0
  - hdf5=1.12.1=h70be1eb_2
  - icu=68.1=h2531618_0
  - idna=3.7=py38h06a4308_0
  - importlib-metadata=7.0.1=py38h06a4308_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipdb=0.13.13=pyhd8ed1ab_0
  - ipython=8.12.2=pyh41d4057_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jpeg=9e=h5eee18b_1
  - keras=2.6.0=pyhd3eb1b0_0
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - krb5=1.20.1=h568e23c_1
  - ld_impl_linux-64=2.38=h1181459_1
  - libcurl=8.2.1=h91b91d3_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.3=he6710b0_2
  - libgcc=14.1.0=h77fa898_1
  - libgcc-ng=14.1.0=h69a702a_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=14.1.0=h77fa898_1
  - libnghttp2=1.52.0=ha637b67_1
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.15=h37d81fd_1
  - libprotobuf=3.14.0=h8c45485_0
  - libssh2=1.10.0=h37d81fd_2
  - libstdcxx=14.1.0=hc0a3c3a_1
  - libstdcxx-ng=14.1.0=h4852527_1
  - markdown=3.4.1=py38h06a4308_0
  - markupsafe=2.1.3=py38h5eee18b_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - multidict=6.0.4=py38h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - numexpr=2.8.4=py38he184ba9_0
  - numpy=1.24.3=py38h14f4228_0
  - numpy-base=1.24.3=py38h31eccc5_0
  - oauthlib=3.2.2=py38h06a4308_0
  - openssl=1.1.1w=hd590300_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - packaging=23.2=py38h06a4308_0
  - pandas=2.0.3=py38h01efb38_1
  - parso=0.8.4=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=24.0=py38h06a4308_0
  - platformdirs=3.10.0=py38h06a4308_0
  - pooch=1.7.0=py38h06a4308_0
  - prompt-toolkit=3.0.48=pyha770c72_0
  - prompt_toolkit=3.0.48=hd8ed1ab_0
  - protobuf=3.14.0=py38h2531618_1
  - psycopg2=2.9.9=py38h5eee18b_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pyjwt=2.4.0=py38h06a4308_0
  - pyodbc=5.0.1=py38h6a678d5_0
  - pyopenssl=23.2.0=py38h06a4308_0
  - python=3.8.10=h12debd9_8
  - python-dateutil=2.9.0post0=py38h06a4308_0
  - python-flatbuffers=1.12=pyhd3eb1b0_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.8=2_cp38
  - pytz=2024.1=py38h06a4308_0
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=py38h06a4308_1
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - scipy=1.10.1=py38h14f4228_0
  - setuptools=69.5.1=py38h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.1.10=h6a678d5_1
  - sqlglot=25.24.4=pyhd8ed1ab_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tensorboard=2.6.0=py_1
  - tensorboard-data-server=0.6.1=py38h52d8a92_0
  - tensorboard-plugin-wit=1.8.1=py38h06a4308_0
  - tensorflow=2.6.0=mkl_py38h874c8e8_0
  - tensorflow-base=2.6.0=mkl_py38h3d85931_0
  - tensorflow-estimator=2.6.0=pyh7b7c402_0
  - termcolor=2.1.0=py38h06a4308_0
  - tk=8.6.14=h39e8969_0
  - toml=0.10.2=pyhd8ed1ab_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing_extensions=4.9.0=py38h06a4308_1
  - unixodbc=2.3.11=h5eee18b_0
  - urllib3=2.1.0=py38h06a4308_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - werkzeug=2.3.8=py38h06a4308_0
  - wheel=0.35.1=pyhd3eb1b0_0
  - wrapt=1.14.1=py38h5eee18b_0
  - xz=5.4.6=h5eee18b_1
  - yarl=1.9.3=py38h5eee18b_0
  - zipp=3.17.0=py38h06a4308_0
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - contourpy==1.1.1
      - cycler==0.12.1
      - fonttools==4.51.0
      - importlib-resources==6.4.0
      - kiwisolver==1.4.5
      - matplotlib==3.7.5
      - pillow==10.3.0
      - pyparsing==3.1.2
      - seaborn==0.13.2
prefix: /home/sclai/bin/miniconda3/envs/dbabandits
